GET http://localhost:9000/users

###
POST http://localhost:9000/users
Content-Type: application/json

{
    "name":"nidhu",
    "email":"nidhu@gmail.com",
    "phone":45,
    "password":"qww"
}

###
GET http://localhost:9000/users/6612e46224332910f5b5b7e8

###
PUT http://localhost:9000/users/6612e5f26bedbaba9cd42d32
Content-Type: application/json

{
    "name":"Neeraj",
    "email":"jjih@gmail.com",
    "phone":39080003
}

###
DELETE http://localhost:9000/users/6661f176af5edaec474ba514

###
POST http://localhost:9000/users/login
Content-Type: application/json

{
    "email":"nidhu@gmail.com",
    "password":"qww"
}

###
POST http://localhost:9000/users/register
Content-Type: application/json

{
    "email":"abcde@gmail.com",
    "password":"abcd"
}